// <auto-generated />
using MS.Infrastructure.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MS.Infrastructure.Migrations
{
    [DbContext(typeof(MSContext))]
    [Migration("20201003023931_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobileModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Processor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mobiles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Apple",
                            Memory = "4GB",
                            Name = "Iphone 11 pro",
                            OS = "IOS",
                            Price = 3500m,
                            Processor = "hexa-core Apple A13",
                            Resolution = "2436 x 1125",
                            ScreenSize = "5.8 inch",
                            Weight = "188g"
                        },
                        new
                        {
                            ID = 2,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Apple",
                            Memory = "3GB",
                            Name = "Iphone 7",
                            OS = "IOS",
                            Price = 1800m,
                            Processor = "hexa-core Apple A9",
                            Resolution = "2436 x 1125",
                            ScreenSize = "4.7 inch",
                            Weight = "159g"
                        },
                        new
                        {
                            ID = 3,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Samsung",
                            Memory = "6GB",
                            Name = "Galaxy s20",
                            OS = "Android",
                            Price = 3500m,
                            Processor = "Snapdragon 855",
                            Resolution = "2436 x 1125",
                            ScreenSize = "6.1 inch",
                            Weight = "188g"
                        });
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobilePhotoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MobileID");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobileVideoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MobileID");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Link = "http://google.com",
                            MobileID = 1
                        });
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobilePhotoModel", b =>
                {
                    b.HasOne("MS.Infrastructure.DAL.Models.MobileModel", "Mobile")
                        .WithMany("Photos")
                        .HasForeignKey("MobileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobileVideoModel", b =>
                {
                    b.HasOne("MS.Infrastructure.DAL.Models.MobileModel", "Mobile")
                        .WithMany("Videos")
                        .HasForeignKey("MobileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
