// <auto-generated />
using MS.Infrastructure.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MS.Infrastructure.Migrations
{
    [DbContext(typeof(MSContext))]
    partial class MSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobileModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Processor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mobiles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Apple",
                            Memory = "4GB",
                            Name = "Iphone 11 pro",
                            OS = "IOS",
                            Price = 3500m,
                            Processor = "hexa-core Apple A13",
                            Resolution = "2436 x 1125",
                            ScreenSize = "5.8 inch",
                            Weight = "188g"
                        },
                        new
                        {
                            ID = 2,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Apple",
                            Memory = "3GB",
                            Name = "Iphone 7",
                            OS = "IOS",
                            Price = 1800m,
                            Processor = "hexa-core Apple A9",
                            Resolution = "2436 x 1125",
                            ScreenSize = "4.7 inch",
                            Weight = "159g"
                        },
                        new
                        {
                            ID = 3,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Samsung",
                            Memory = "6GB",
                            Name = "Galaxy s20",
                            OS = "Android",
                            Price = 3500m,
                            Processor = "Snapdragon 855",
                            Resolution = "2436 x 1125",
                            ScreenSize = "6.1 inch",
                            Weight = "188g"
                        },
                        new
                        {
                            ID = 4,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Samsung",
                            Memory = "3GB",
                            Name = "Galaxy s4",
                            OS = "Android",
                            Price = 1234m,
                            Processor = "Snapdragon 650",
                            Resolution = "1200 x 850",
                            ScreenSize = "5.0 inch",
                            Weight = "145g"
                        },
                        new
                        {
                            ID = 5,
                            Dimensions = "130mm X 65.4mm X 7.3mm",
                            Manufacturer = "Huawei",
                            Memory = "2GB",
                            Name = "Honor 4c",
                            OS = "Android",
                            Price = 500m,
                            Processor = "Snapdragon 550",
                            Resolution = "1800 x 850",
                            ScreenSize = "4.7 inch",
                            Weight = "130g"
                        },
                        new
                        {
                            ID = 6,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Huawei",
                            Memory = "4GB",
                            Name = "P30",
                            OS = "Android",
                            Price = 900m,
                            Processor = "Snapdragon 855",
                            Resolution = "2436 x 1125",
                            ScreenSize = "5.7 inch",
                            Weight = "175g"
                        },
                        new
                        {
                            ID = 7,
                            Dimensions = "130mm X 65.5mm X 8.1mm",
                            Manufacturer = "Apple",
                            Memory = "3GB",
                            Name = "Iphone SE",
                            OS = "IOS",
                            Price = 1500m,
                            Processor = "hexa-core Apple A12",
                            Resolution = "1900 x 900",
                            ScreenSize = "4.7 inch",
                            Weight = "160g"
                        },
                        new
                        {
                            ID = 8,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Samsung",
                            Memory = "4GB",
                            Name = "Galaxy A80",
                            OS = "Android",
                            Price = 1700m,
                            Processor = "Snapdragon 855",
                            Resolution = "2436 x 1125",
                            ScreenSize = "6.0 inch",
                            Weight = "188g"
                        },
                        new
                        {
                            ID = 9,
                            Dimensions = "162.3mm X 77.2mm X 8.9mm",
                            Manufacturer = "Xiaomi",
                            Memory = "4GB",
                            Name = "Redmi note 9",
                            OS = "Android",
                            Price = 1499m,
                            Processor = "MediaTek Helio G85",
                            Resolution = "1080 x 2340",
                            ScreenSize = "6.53 inch",
                            Weight = "199g"
                        },
                        new
                        {
                            ID = 10,
                            Dimensions = "144mm X 71.4mm X 8.1mm",
                            Manufacturer = "Nokia",
                            Memory = "32GB 2GB RAM",
                            Name = "Lumia 1020",
                            OS = "Windows Phone",
                            Price = 120m,
                            Processor = "Snapdragon S4 Plus",
                            Resolution = "1280 x 768",
                            ScreenSize = "4.5 inch",
                            Weight = "158g"
                        });
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobilePhotoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MobileID");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Link = "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-11-pro-max-4.jpg",
                            MobileID = 1
                        },
                        new
                        {
                            ID = 11,
                            Link = "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro-max-.jpg",
                            MobileID = 1
                        },
                        new
                        {
                            ID = 2,
                            Link = "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-7-3.jpg",
                            MobileID = 2
                        },
                        new
                        {
                            ID = 3,
                            Link = "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-ultra-.jpg",
                            MobileID = 3
                        },
                        new
                        {
                            ID = 4,
                            Link = "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s-4-i9500-black-mist.jpg",
                            MobileID = 4
                        },
                        new
                        {
                            ID = 5,
                            Link = "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-honor-4c-1.jpg",
                            MobileID = 5
                        },
                        new
                        {
                            ID = 6,
                            Link = "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p30-1.jpg",
                            MobileID = 6
                        },
                        new
                        {
                            ID = 7,
                            Link = "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2020.jpg",
                            MobileID = 7
                        },
                        new
                        {
                            ID = 8,
                            Link = "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a80-.jpg",
                            MobileID = 8
                        },
                        new
                        {
                            ID = 9,
                            Link = "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-redmi-note-9-4.jpg",
                            MobileID = 9
                        },
                        new
                        {
                            ID = 10,
                            Link = "https://fdn2.gsmarena.com/vv/pics/nokia/nokia-lumia-1020.jpg",
                            MobileID = 10
                        });
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobileVideoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobileID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MobileID");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Link = "https://www.youtube.com/watch?v=OoY7zp8GkLI&ab_channel=MarquesBrownlee",
                            MobileID = 1
                        },
                        new
                        {
                            ID = 2,
                            Link = "https://www.youtube.com/watch?v=nxf41fMX_Y4&ab_channel=MarquesBrownlee",
                            MobileID = 2
                        },
                        new
                        {
                            ID = 3,
                            Link = "https://www.youtube.com/watch?v=ZdC9soHxVC8&ab_channel=MarquesBrownlee",
                            MobileID = 3
                        },
                        new
                        {
                            ID = 4,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 4
                        },
                        new
                        {
                            ID = 5,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 5
                        },
                        new
                        {
                            ID = 6,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 6
                        },
                        new
                        {
                            ID = 7,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 7
                        },
                        new
                        {
                            ID = 8,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 8
                        },
                        new
                        {
                            ID = 9,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 9
                        },
                        new
                        {
                            ID = 10,
                            Link = "https://www.youtube.com/watch?v=zrc2UAMnr94&ab_channel=UnboxTherapy",
                            MobileID = 10
                        });
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobilePhotoModel", b =>
                {
                    b.HasOne("MS.Infrastructure.DAL.Models.MobileModel", "Mobile")
                        .WithMany("Photos")
                        .HasForeignKey("MobileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MS.Infrastructure.DAL.Models.MobileVideoModel", b =>
                {
                    b.HasOne("MS.Infrastructure.DAL.Models.MobileModel", "Mobile")
                        .WithMany("Videos")
                        .HasForeignKey("MobileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
